---
- name: testing webhook
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: messaging teams
      cisco_spark:
        recipient_type: roomId
        recipient_id: "Y2lzY29zcGFyazovL3VzL1JPT00vYmQ1OWEyNDAtMjg3YS0xMWU5LTgwOTItN2YwZmZmMGU0Mjg1""
        message_type: text
        personal_token: "ZmYwMjRmYjEtNWM4ZC00NGQ0LTk3NmMtNTZhZDE1ZmM0OTc4ZDEzMTk4OWUtMDhj_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
        message: "This is a test" 
