---
- name: testing webhook
  hosts: local
  gather_facts: no
  connection: local

  tasks:
    - name: Setting default values
      set_fact:
        RoomId: "Somthing went wrong"
        IP: "Somthing went wrong"

    - name: DEBUG| getting room ID
      debug:
        var: RoomId

    - name: DEBUG | Getting IP
      debug:
        var: IP

    - name: messaging teams
      cisco_spark:
        recipient_type: roomId
        recipient_id: "{{RoomId}}"
        message_type: text
        personal_token: "ZmYwMjRmYjEtNWM4ZC00NGQ0LTk3NmMtNTZhZDE1ZmM0OTc4ZDEzMTk4OWUtMDhj_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
        message: "{{IP}}"
